# Generated by Django 3.0.7 on 2020-07-09 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lang_translator', '0002_auto_20200707_1816'),
    ]

    operations = [
        migrations.AlterField(
            model_name='audio',
            name='audio',
            field=models.FileField(upload_to='media/'),
        ),
    ]
